[dev]

[dev."server"]
database_url = "postgresql://postgres:bj123456@localhost/feel-server"
host = "0.0.0.0"
port = 9000

[dev."system"]
name = "feel-server"
version = "0.0.0"

[production]

[production."server"]
database_url = "postgresql://postgres:bj123456@localhost/feel-server"
host = "0.0.0.0"
port = 9000

[production."system"]
name = "feel-server"
version = "0.0.0"
