[dev]

[dev.server]
database_url = "postgresql://postgres:bj123456@localhost/feel-server"
host = "0.0.0.0"
port = 9000

[dev.system]
name = "feel-server"
version = "0.0.0"

[dev.encrypt]
secure = "feel"

[dev.jwt]
secure = "feel"
issuer = "feel.com"

[production]

[production.server]
database_url = "postgresql://postgres:bj123456@localhost/feel-server"
host = "0.0.0.0"
port = 9000

[production.system]
name = "feel-server"
version = "0.0.0"

[production.encrypt]
secure = "feel"

[production.jwt]
secure = "feel"
issuer = "feel.com"
